apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # SÉCURITÉ : Configuration du Pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: frontend
        image: cinema-frontend:latest
        imagePullPolicy: IfNotPresent
        # SÉCURITÉ : Configuration du Conteneur
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5173